### ISSUE TITLE
Consider the possibility of support for WebFlux Framwork

### ISSUE THREAD

**Issue by tangcent** [tangcent/easy-api#132]
# TODO LIST

- [x] Spring WebFlux Demo 
- [x] Spring WebFlux + Kotlin Demo 
- [x] Support export Spring WebFlux
- [x] Support export Spring WebFlux + Kotlin 

---

# [WebFlux Framwork](https://docs.spring.io/spring-framework/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/web-reactive.html)

### [Request and Response Body Conversion](https://docs.spring.io/spring-framework/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/web-reactive.html#web-reactive-http-body)

For example the request body can be one of the following way and it will be decoded automatically in both the annotation and the functional programming models:

Account account — the account is deserialized without blocking before the controller is invoked.
- Mono\<Account> account — the controller can use the Mono to declare logic to be executed - after the account is deserialized.
- Single\<Account> account — same as with Mono but using RxJava
- Flux\<Account> accounts — input streaming scenario.
- Observable\<Account> accounts — input streaming with RxJava.
The response body can be one of the following:

- Mono\<Account> — serialize without blocking the given Account when the Mono completes.
- Single\<Account> — same but using RxJava.
- Flux\<Account> — streaming scenario, possibly SSE depending on the requested content type.
- Observable\<Account> — same but using RxJava Observable type.
- Flowable\<Account> — same but using RxJava 2 Flowable type.
- Flux\<ServerSentEvent> — SSE streaming.
- Mono\<Void> — request handling completes when the Mono completes.
- Account — serialize without blocking the given Account; implies a synchronous, non-blocking controller method.
- void — specific to the annotation-based programming model, request handling completes when the method returns; implies a synchronous, non-blocking controller method.

When using stream types like Flux or Observable, the media type specified in the request/response or at mapping/routing level is used to determine how the data should be serialized and flushed. For example a REST endpoint that returns a Flux<User> will be serialized by default as following:

- application/json: a Flux\<User> is handled as an asynchronous collection and serialized as a JSON array with an explicit flush when the complete event is emitted.
- application/stream+json: a Flux\<User> will be handled as a stream of User elements serialized as individual JSON object separated by new lines and explicitly flushed after each element. The WebClient supports JSON stream decoding so this is a good use case for server to server use case.
- text/event-stream: a Flux\<User> or Flux\<ServerSentEvent<User>> will be handled as a stream of User or ServerSentEvent elements serialized as individual SSE elements using by default JSON for data encoding and explicit flush after each element. This is well suited for exposing a stream to browser clients. WebClient supports reading SSE streams as well.

**Comment by tangcent** [comment]
- #133
